export interface BotLevel {
  rating: number;
  name: string;
  personality: string;
  avatar: string;
}

export const botLevels: BotLevel[] = [
    { rating: 250, name: "Newcomer Ned", personality: "Just learned the rules, might make some illegal moves.", avatar: "/avatars/bot-0.png" },
    { rating: 300, name: "Rookie Rita", personality: "Focuses on capturing pieces, often missing threats.", avatar: "/avatars/bot-1.png" },
    { rating: 350, name: "Apprentice Ana", personality: "Understands basic tactics but easily falls for traps.", avatar: "/avatars/bot-2.png" },
    { rating: 400, name: "Beginner Ben", personality: "Starts to develop pieces but has no clear plan.", avatar: "/avatars/bot-3.png" },
    { rating: 450, name: "Novice Noah", personality: "Can spot one-move threats but misses longer combinations.", avatar: "/avatars/bot-4.png" },
    { rating: 500, name: "Learner Leo", personality: "Tries to control the center but can be outmaneuvered.", avatar: "/avatars/bot-5.png" },
    { rating: 550, name: "Aspirant Aria", personality: "Loves to attack, sometimes forgetting to defend.", avatar: "/avatars/bot-6.png" },
    { rating: 600, name: "Hobbyist Hank", personality: "Knows a few opening lines but quickly goes off-book.", avatar: "/avatars/bot-7.png" },
    { rating: 650, name: "Enthusiast Eva", personality: "Enjoys creative moves, even if they aren't the best.", avatar: "/avatars/bot-8.png" },
    { rating: 700, name: "Player Pete", personality: "A solid player who understands piece value.", avatar: "/avatars/bot-9.png" },
    { rating: 750, name: "Regular Sam", personality: "Plays consistently but can be predictable.", avatar: "/avatars/bot-10.png" },
    { rating: 800, name: "Intermediate Ivy", personality: "Good at spotting forks and pins, but not always executing.", avatar: "/avatars/bot-11.png" },
    { rating: 850, name: "Club Player Carl", personality: "Enjoys long games and positional struggles.", avatar: "/avatars/bot-12.png" },
    { rating: 900, name: "Steady Stella", personality: "A very cautious player who rarely makes mistakes.", avatar: "/avatars/bot-13.png" },
    { rating: 950, name: "Experienced Eric", personality: "Has seen many patterns and uses them well.", avatar: "/avatars/bot-14.png" },
    { rating: 1000, name: "Adept Alex", personality: "A balanced player with a good understanding of all phases.", avatar: "/avatars/bot-15.png" },
    { rating: 1050, name: "Strategist Sofia", personality: "Thinks several moves ahead and formulates plans.", avatar: "/avatars/bot-16.png" },
    { rating: 1100, name: "Tactician Tom", personality: "Loves to calculate complex variations.", avatar: "/avatars/bot-17.png" },
    { rating: 1150, name: "Advanced Ada", personality: "Punishes inaccuracies with precision.", avatar: "/avatars/bot-18.png" },
    { rating: 1200, name: "Skilled Simon", personality: "A sharp player who is always looking for an edge.", avatar: "/avatars/bot-19.png" },
    { rating: 1250, name: "Proficient Penny", personality: "Converts advantages into wins effectively.", avatar: "/avatars/bot-20.png" },
    { rating: 1300, name: "Challenger Chad", personality: "Plays aggressively and puts pressure on his opponents.", avatar: "/avatars/bot-21.png" },
    { rating: 1350, name: "Veteran Vera", personality: "Uses experience to navigate tricky endgames.", avatar: "/avatars/bot-22.png" },
    { rating: 1400, name: "Sharp Susan", personality: "Extremely accurate in tactical calculations.", avatar: "/avatars/bot-23.png" },
    { rating: 1450, name: "Seasoned Stan", personality: "A calm and collected player, unflustered by attacks.", avatar: "/avatars/bot-24.png" },
    { rating: 1500, name: "Expert Emily", personality: "Has a deep knowledge of opening theory.", avatar: "/avatars/bot-25.png" },
    { rating: 1550, name: "Specialist Spencer", personality: "Excels in a particular type of position, like closed games.", avatar: "/avatars/bot-26.png" },
    { rating: 1600, name: "Candidate Chris", personality: "Plays with the ambition of a future master.", avatar: "/avatars/bot-27.png" },
    { rating: 1650, name: "Strong Steve", personality: "A powerful player who gives no quarter.", avatar: "/avatars/bot-28.png" },
    { rating: 1700, name: "Elite Elara", personality: "Creative and unpredictable, a formidable opponent.", avatar: "/avatars/bot-29.png" },
    { rating: 1750, name: "Dominant Diana", personality: "Controls the board with an iron grip.", avatar: "/avatars/bot-30.png" },
    { rating: 1800, name: "Formidable Fred", personality: "Relentless in attack, stubborn in defense.", avatar: "/avatars/bot-31.png" },
    { rating: 1850, name: "Mighty Maya", personality: "A dynamic player who can turn defense into offense in a flash.", avatar: "/avatars/bot-32.png" },
    { rating: 1900, name: "Fierce Fiona", personality: "Never backs down from a fight, loves sharp positions.", avatar: "/avatars/bot-33.png" },
    { rating: 1950, name: "Tournament Pro", personality: "Plays like a seasoned tournament competitor.", avatar: "/avatars/bot-34.png" },
    { rating: 2000, name: "Mastermind Max", personality: "A true master of strategy and tactics.", avatar: "/avatars/bot-35.png" },
    { rating: 2050, name: "Senior Master", personality: "Decades of experience packed into every move.", avatar: "/avatars/bot-36.png" },
    { rating: 2100, name: "National Master", personality: "Plays at a nationally recognized level of excellence.", avatar: "/avatars/bot-37.png" },
    { rating: 2150, name: "FIDE Master", personality: "An internationally titled player with a flair for the dramatic.", avatar: "/avatars/bot-38.png" },
    { rating: 2200, name: "International Master", personality: "A brilliant mind, capable of stunning sacrifices.", avatar: "/avatars/bot-39.png" },
    { rating: 2250, name: "Grandmaster Candidate", personality: "On the cusp of chess greatness, plays with fire.", avatar: "/avatars/bot-40.png" },
    { rating: 2300, name: "Grandmaster Igor", personality: "A living legend of the game. Every move is a lesson.", avatar: "/avatars/bot-41.png" },
    { rating: 2350, name: "Super Grandmaster", personality: "One of the world's elite. Almost flawless play.", avatar: "/avatars/bot-42.png" },
    { rating: 2400, name: "Champion", personality: "Plays with the confidence and power of a world champion.", avatar: "/avatars/bot-43.png" },
    { rating: 2450, name: "World Class", personality: "In a league of their own. Truly world-class.", avatar: "/avatars/bot-44.png" },
    { rating: 2500, name: "Legend", personality: "A mythical figure in the chess world. Plays like a god.", avatar: "/avatars/bot-45.png" },
    { rating: 2550, name: "Titan", personality: "A giant of the game, crushing all in their path.", avatar: "/avatars/bot-46.png" },
    { rating: 2600, name: "Virtuoso", personality: "A chess artist, painting masterpieces on the board.", avatar: "/avatars/bot-47.png" },
    { rating: 2650, name: "Genius", personality: "A once-in-a-generation talent. Sees everything.", avatar: "/avatars/bot-48.png" },
    { rating: 2700, name: "Prodigy", personality: "Effortlessly brilliant, destined for the top.", avatar: "/avatars/bot-49.png" },
    { rating: 2750, name: "Phenom", personality: "A phenomenon of the chess world. Unstoppable.", avatar: "/avatars/bot-50.png" },
    { rating: 2800, name: "Maestro", personality: "Conducts the pieces like an orchestra.", avatar: "/avatars/bot-51.png" },
    { rating: 2850, name: "The Oracle", personality: "Sees the future of the game with eerie accuracy.", avatar: "/avatars/bot-52.png" },
    { rating: 2900, name: "The Thinker", personality: "Deep in thought, calculating lines you've never imagined.", avatar: "/avatars/bot-53.png" },
    { rating: 2950, name: "The Engine", personality: "Plays with cold, hard, machinelike precision.", avatar: "/avatars/bot-54.png" },
    { rating: 3000, name: "The Centaur", personality: "The perfect fusion of human creativity and machine calculation.", avatar: "/avatars/bot-55.png" },
    { rating: 3050, name: "Deep Thought", personality: "A super-intelligence from another dimension.", avatar: "/avatars/bot-56.png" },
    { rating: 3100, name: "Alpha", personality: "The first and the last word in chess. The ultimate AI.", avatar: "/avatars/bot-57.png" },
    { rating: 3150, name: "Stockfish Level", personality: "Plays at the level of the strongest chess engine.", avatar: "/avatars/bot-58.png" },
    { rating: 3200, name: "Ultimate AI", personality: "Beyond human comprehension. The pinnacle of chess.", avatar: "/avatars/bot-59.png" }
];
